
#nodework

FROM node:16.3.0-alpine as nodework
WORKDIR /myapp
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

#nginx


FROM nginx:1.23-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=nodework /myapp/build .

ENTRYPOINT ["nginx", "-g", "daemon off;"]

